# Generated by Django 6.0.4 on 2026-04-26 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_socialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="splits",
                to="api.transaction",
            ),
        ),
    ]
