# Generated by Django 6.0.4 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_transaction_parent_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="external_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
