# Generated by Django 6.0 migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_transaction_transaction_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringpattern",
            name="category",
        ),
    ]
