# Generated by Django 6.0 migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_recurringpattern_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringpattern",
            name="match_type",
            field=models.CharField(
                choices=[("PARTIAL", "Partial"), ("EXACT", "Exact")],
                default="PARTIAL",
                max_length=10,
            ),
        ),
    ]
