# Generated by Django 6.0 migration

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_recurringpattern_match_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recurringpattern",
            constraint=models.UniqueConstraint(
                condition=Q(user__isnull=False),
                fields=("user", "match_type", "description_pattern"),
                name="api_recurringpattern_user_matchtype_pattern_uniq",
            ),
        ),
    ]
