/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#aec7f7',
        'on-primary-container': '#7a93c0',
        'secondary-fixed-dim': '#59dbc7',
        'on-tertiary-fixed-variant': '#34495e',
        background: '#f3faff',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#aec7f7',
        'surface-variant': '#cfe6f2',
        'surface-dim': '#c7dde9',
        'on-primary-fixed-variant': '#2d476f',
        'primary-fixed': '#d6e3ff',
        'on-error-container': '#93000a',
        'surface-container-low': '#e6f6ff',
        surface: '#f3faff',
        'error-container': '#ffdad6',
        'surface-tint': '#465f89',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#cfe6f2',
        'on-primary-fixed': '#001b3d',
        error: '#ba1a1a',
        'surface-container': '#dbf1fe',
        'on-surface': '#071e27',
        'inverse-on-surface': '#dff4ff',
        secondary: '#006b5f',
        'surface-container-high': '#d5ecf8',
        'tertiary-fixed-dim': '#b3c9e2',
        'on-tertiary-container': '#7f95ad',
        primary: '#001634',
        'surface-bright': '#f3faff',
        'on-background': '#071e27',
        'secondary-container': '#76f4e0',
        'outline-variant': '#c4c6cf',
        outline: '#74777f',
        'on-surface-variant': '#44474e',
        'on-secondary-container': '#006f63',
        'secondary-fixed': '#79f7e3',
        'on-tertiary-fixed': '#051d30',
        'tertiary-fixed': '#cfe5ff',
        'primary-container': '#0d2b52',
        'inverse-surface': '#1e333c',
        'on-secondary-fixed': '#00201c',
        tertiary: '#01182b',
        'tertiary-container': '#172d41',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#005047',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
